"""
LaTeX Grammar Validator for OCR Output.
Provides structural and semantic validation of LaTeX expressions
generated by math OCR models, going beyond simple brace balancing.
"""

import re
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, field


@dataclass
class ValidationResult:
    """Result of LaTeX validation."""
    is_valid: bool
    corrected_latex: str
    violations: List[Dict] = field(default_factory=list)
    confidence_modifier: float = 1.0  # Multiplier for OCR confidence


# LaTeX commands that require exactly N arguments
COMMAND_ARG_COUNTS = {
    r"\frac": 2,
    r"\binom": 2,
    r"\overset": 2,
    r"\underset": 2,
    r"\stackrel": 2,
    r"\cfrac": 2,
    r"\dfrac": 2,
    r"\tfrac": 2,
    r"\sqrt": 1,       # Optional [] + required {}
    r"\hat": 1,
    r"\bar": 1,
    r"\vec": 1,
    r"\dot": 1,
    r"\ddot": 1,
    r"\tilde": 1,
    r"\widetilde": 1,
    r"\widehat": 1,
    r"\overline": 1,
    r"\underline": 1,
    r"\overbrace": 1,
    r"\underbrace": 1,
    r"\mathbb": 1,
    r"\mathbf": 1,
    r"\mathcal": 1,
    r"\mathfrak": 1,
    r"\mathrm": 1,
    r"\mathit": 1,
    r"\mathsf": 1,
    r"\text": 1,
    r"\textbf": 1,
    r"\textit": 1,
    r"\operatorname": 1,
    r"\boldsymbol": 1,
}

# LaTeX environments that must have matching \begin{} and \end{}
ENVIRONMENTS = [
    "matrix", "pmatrix", "bmatrix", "Bmatrix", "vmatrix", "Vmatrix",
    "array", "align", "aligned", "equation", "gather", "gathered",
    "cases", "split", "multline", "subarray",
]

# Commands that don't take arguments (no braces expected)
NO_ARG_COMMANDS = {
    r"\alpha", r"\beta", r"\gamma", r"\delta", r"\epsilon", r"\zeta",
    r"\eta", r"\theta", r"\iota", r"\kappa", r"\lambda", r"\mu",
    r"\nu", r"\xi", r"\pi", r"\rho", r"\sigma", r"\tau", r"\upsilon",
    r"\phi", r"\chi", r"\psi", r"\omega",
    r"\Gamma", r"\Delta", r"\Theta", r"\Lambda", r"\Xi", r"\Pi",
    r"\Sigma", r"\Upsilon", r"\Phi", r"\Psi", r"\Omega",
    r"\infty", r"\partial", r"\nabla", r"\forall", r"\exists",
    r"\cdot", r"\cdots", r"\ldots", r"\vdots", r"\ddots",
    r"\quad", r"\qquad", r"\hspace", r"\vspace",
    r"\sin", r"\cos", r"\tan", r"\cot", r"\sec", r"\csc",
    r"\arcsin", r"\arccos", r"\arctan",
    r"\log", r"\ln", r"\exp", r"\lim", r"\max", r"\min",
    r"\sum", r"\prod", r"\int", r"\oint", r"\iint", r"\iiint",
    r"\pm", r"\mp", r"\times", r"\div", r"\neq", r"\leq", r"\geq",
    r"\approx", r"\equiv", r"\sim", r"\simeq", r"\propto",
    r"\in", r"\notin", r"\subset", r"\supset", r"\subseteq", r"\supseteq",
    r"\cup", r"\cap", r"\setminus", r"\emptyset",
    r"\rightarrow", r"\leftarrow", r"\Rightarrow", r"\Leftarrow",
    r"\leftrightarrow", r"\Leftrightarrow", r"\to", r"\gets",
    r"\uparrow", r"\downarrow", r"\mapsto",
    r"\left", r"\right", r"\big", r"\Big", r"\bigg", r"\Bigg",
}


class LaTeXGrammarValidator:
    """
    Validates and corrects LaTeX output from OCR models.
    Goes beyond brace balancing to check structural and semantic correctness.
    """

    def __init__(self, auto_correct: bool = True):
        """
        Args:
            auto_correct: Whether to attempt automatic corrections
        """
        self.auto_correct = auto_correct

    def validate(self, latex: str) -> ValidationResult:
        """
        Validate a LaTeX expression.

        Args:
            latex: Raw LaTeX string from OCR

        Returns:
            ValidationResult with validity flag, corrected LaTeX, and violations
        """
        violations = []
        corrected = latex.strip()
        confidence_modifier = 1.0

        # Run all validation checks
        corrected, v = self._check_brace_balance(corrected)
        violations.extend(v)

        corrected, v = self._check_environment_matching(corrected)
        violations.extend(v)

        corrected, v = self._check_command_arguments(corrected)
        violations.extend(v)

        corrected, v = self._check_delimiter_pairing(corrected)
        violations.extend(v)

        corrected, v = self._check_subscript_superscript(corrected)
        violations.extend(v)

        corrected, v = self._check_common_ocr_errors(corrected)
        violations.extend(v)

        corrected, v = self._check_repetition(corrected)
        violations.extend(v)

        # Calculate confidence modifier based on violations
        for v_item in violations:
            severity = v_item.get("severity", "warning")
            if severity == "error":
                confidence_modifier *= 0.6
            elif severity == "warning":
                confidence_modifier *= 0.85

        confidence_modifier = max(0.1, confidence_modifier)

        is_valid = all(v.get("severity") != "error" for v in violations) or self.auto_correct

        return ValidationResult(
            is_valid=is_valid,
            corrected_latex=corrected,
            violations=violations,
            confidence_modifier=confidence_modifier,
        )

    def _check_brace_balance(self, latex: str) -> Tuple[str, List[Dict]]:
        """Check and fix curly brace balance."""
        violations = []
        open_count = 0
        result = []

        for i, char in enumerate(latex):
            if char == '{':
                open_count += 1
                result.append(char)
            elif char == '}':
                if open_count > 0:
                    open_count -= 1
                    result.append(char)
                else:
                    # Unmatched closing brace — skip it
                    violations.append({
                        "type": "unmatched_close_brace",
                        "position": i,
                        "severity": "warning",
                        "message": f"Removed unmatched '}}' at position {i}",
                    })
            else:
                result.append(char)

        corrected = ''.join(result)

        # Add missing closing braces
        if open_count > 0:
            violations.append({
                "type": "missing_close_braces",
                "count": open_count,
                "severity": "warning",
                "message": f"Added {open_count} missing closing brace(s)",
            })
            corrected += '}' * open_count

        return corrected, violations

    def _check_environment_matching(self, latex: str) -> Tuple[str, List[Dict]]:
        """Check that \\begin{} and \\end{} environments are properly matched."""
        violations = []

        begins = re.findall(r'\\begin\{(\w+)\}', latex)
        ends = re.findall(r'\\end\{(\w+)\}', latex)

        # Check for unmatched begins
        begin_stack = list(begins)
        end_list = list(ends)

        for env in end_list:
            if env in begin_stack:
                begin_stack.remove(env)
            else:
                violations.append({
                    "type": "unmatched_end",
                    "environment": env,
                    "severity": "error",
                    "message": f"\\end{{{env}}} without matching \\begin{{{env}}}",
                })

        for env in begin_stack:
            violations.append({
                "type": "unmatched_begin",
                "environment": env,
                "severity": "error",
                "message": f"\\begin{{{env}}} without matching \\end{{{env}}}",
            })
            # Auto-correct: add missing \end{}
            if self.auto_correct:
                latex += f"\\end{{{env}}}"

        return latex, violations

    def _check_command_arguments(self, latex: str) -> Tuple[str, List[Dict]]:
        """Check that commands have the correct number of arguments."""
        violations = []

        for cmd, expected_args in COMMAND_ARG_COUNTS.items():
            # Find all occurrences of this command
            pattern = re.escape(cmd)
            for match in re.finditer(pattern, latex):
                pos = match.end()
                remaining = latex[pos:]

                # Count consecutive brace groups
                actual_args = 0
                scan_pos = 0

                # Skip optional argument [...]
                stripped = remaining[scan_pos:].lstrip()
                if stripped.startswith('['):
                    bracket_depth = 0
                    for j, c in enumerate(stripped):
                        if c == '[':
                            bracket_depth += 1
                        elif c == ']':
                            bracket_depth -= 1
                            if bracket_depth == 0:
                                scan_pos += j + 1 + (len(remaining[scan_pos:]) - len(stripped))
                                break

                # Count required {} arguments
                for _ in range(expected_args + 1):
                    s = remaining[scan_pos:].lstrip()
                    if s.startswith('{'):
                        depth = 0
                        for j, c in enumerate(s):
                            if c == '{':
                                depth += 1
                            elif c == '}':
                                depth -= 1
                                if depth == 0:
                                    actual_args += 1
                                    scan_pos += j + 1 + (len(remaining[scan_pos:]) - len(s))
                                    break
                    else:
                        break

                if actual_args < expected_args:
                    violations.append({
                        "type": "missing_arguments",
                        "command": cmd,
                        "expected": expected_args,
                        "found": actual_args,
                        "severity": "warning",
                        "message": f"{cmd} expects {expected_args} arg(s), found {actual_args}",
                    })

        return latex, violations

    def _check_delimiter_pairing(self, latex: str) -> Tuple[str, List[Dict]]:
        """Check that \\left and \\right are properly paired."""
        violations = []

        left_count = len(re.findall(r'\\left[\(\[\{|.]', latex))
        right_count = len(re.findall(r'\\right[\)\]\}|.]', latex))

        if left_count != right_count:
            violations.append({
                "type": "delimiter_mismatch",
                "left_count": left_count,
                "right_count": right_count,
                "severity": "warning",
                "message": f"\\left (×{left_count}) and \\right (×{right_count}) count mismatch",
            })

            # Auto-correct: add missing \right. or \left.
            if self.auto_correct:
                if left_count > right_count:
                    latex += "\\right." * (left_count - right_count)
                else:
                    latex = "\\left." * (right_count - left_count) + latex

        return latex, violations

    def _check_subscript_superscript(self, latex: str) -> Tuple[str, List[Dict]]:
        """Check for empty or malformed subscripts/superscripts."""
        violations = []

        # Empty subscripts: _{} or _{ }
        empty_sub = re.findall(r'_\{\s*\}', latex)
        if empty_sub:
            violations.append({
                "type": "empty_subscript",
                "count": len(empty_sub),
                "severity": "warning",
                "message": f"Found {len(empty_sub)} empty subscript(s)",
            })
            if self.auto_correct:
                latex = re.sub(r'_\{\s*\}', '', latex)

        # Empty superscripts: ^{} or ^{ }
        empty_sup = re.findall(r'\^\{\s*\}', latex)
        if empty_sup:
            violations.append({
                "type": "empty_superscript",
                "count": len(empty_sup),
                "severity": "warning",
                "message": f"Found {len(empty_sup)} empty superscript(s)",
            })
            if self.auto_correct:
                latex = re.sub(r'\^\{\s*\}', '', latex)

        # Double subscript/superscript without braces: x__a or x^^a
        if re.search(r'_{2,}', latex) or re.search(r'\^{2,}', latex):
            violations.append({
                "type": "double_script",
                "severity": "error",
                "message": "Double subscript or superscript detected",
            })
            if self.auto_correct:
                latex = re.sub(r'_{2,}', '_', latex)
                latex = re.sub(r'\^{2,}', '^', latex)

        return latex, violations

    def _check_common_ocr_errors(self, latex: str) -> Tuple[str, List[Dict]]:
        """Fix common OCR-specific LaTeX errors."""
        violations = []
        original = latex

        # Common misrecognitions
        ocr_fixes = [
            # Spacing fixes
            (r'\\\s+frac', r'\\frac', "space_in_frac"),
            (r'\\\s+sqrt', r'\\sqrt', "space_in_sqrt"),
            (r'\\\s+sum', r'\\sum', "space_in_sum"),
            (r'\\\s+int', r'\\int', "space_in_int"),
            (r'\\\s+lim', r'\\lim', "space_in_lim"),
            (r'\\\s+text', r'\\text', "space_in_text"),
            # Extra spaces inside braces
            (r'\{\s+', r'{', "space_after_open_brace"),
            (r'\s+\}', r'}', "space_before_close_brace"),
            # Common OCR character confusions
            (r'\\Irac', r'\\frac', "l_to_f_in_frac"),
            (r'\\sqnt', r'\\sqrt', "n_to_r_in_sqrt"),
            (r'\\fracl', r'\\frac{', "missing_brace_after_frac"),
        ]

        for pattern, replacement, fix_type in ocr_fixes:
            new_latex = re.sub(pattern, replacement, latex)
            if new_latex != latex:
                violations.append({
                    "type": f"ocr_fix_{fix_type}",
                    "severity": "info",
                    "message": f"Applied OCR correction: {fix_type}",
                })
                latex = new_latex

        return latex, violations

    def _check_repetition(self, latex: str) -> Tuple[str, List[Dict]]:
        """Detect and fix repetitive patterns (hallucination indicator)."""
        violations = []

        # Detect repeated tokens (e.g., "\frac\frac\frac")
        repeated = re.findall(r'(\\[a-zA-Z]+)\1{2,}', latex)
        if repeated:
            violations.append({
                "type": "repeated_commands",
                "commands": repeated,
                "severity": "error",
                "message": f"Repeated command pattern detected: {repeated}",
            })
            if self.auto_correct:
                for cmd in repeated:
                    pattern = re.escape(cmd) + r'(?:' + re.escape(cmd) + r')+'
                    latex = re.sub(pattern, cmd, latex)

        # Detect character repetition (e.g., "aaaaaaa")
        char_repeat = re.findall(r'([a-zA-Z])\1{4,}', latex)
        if char_repeat:
            violations.append({
                "type": "repeated_characters",
                "severity": "error",
                "message": f"Excessive character repetition detected",
            })
            if self.auto_correct:
                latex = re.sub(r'([a-zA-Z])\1{4,}', r'\1', latex)

        return latex, violations


class LaTeXCorrector:
    """
    Higher-level LaTeX corrector that combines grammar validation
    with semantic fixes and optional LLM-based correction.
    """

    def __init__(self, use_llm: bool = False):
        """
        Args:
            use_llm: Whether to use LLM for difficult corrections
        """
        self.validator = LaTeXGrammarValidator(auto_correct=True)
        self.use_llm = use_llm

    def correct(self, latex: str, image_context: Optional[str] = None) -> Tuple[str, float]:
        """
        Correct LaTeX expression.

        Args:
            latex: Raw LaTeX from OCR
            image_context: Optional description of the image for LLM context

        Returns:
            Tuple of (corrected_latex, confidence_modifier)
        """
        # Step 1: Grammar validation and basic correction
        result = self.validator.validate(latex)

        # Step 2: If many violations and LLM available, try LLM correction
        error_count = sum(1 for v in result.violations if v.get("severity") == "error")
        if error_count > 2 and self.use_llm:
            llm_corrected = self._llm_correct(result.corrected_latex, image_context)
            if llm_corrected:
                # Re-validate LLM output
                llm_result = self.validator.validate(llm_corrected)
                if len(llm_result.violations) < len(result.violations):
                    return llm_result.corrected_latex, llm_result.confidence_modifier
                    
        return result.corrected_latex, result.confidence_modifier

    def _llm_correct(self, latex: str, context: Optional[str] = None) -> Optional[str]:
        """Use LLM to correct difficult LaTeX expressions."""
        try:
            import openai

            prompt = (
                "Fix any LaTeX errors in the following mathematical expression. "
                "Return ONLY the corrected LaTeX, nothing else.\n\n"
                f"Input: {latex}"
            )
            if context:
                prompt += f"\nContext: {context}"

            client = openai.OpenAI()
            response = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=512,
                temperature=0.0,
            )
            return response.choices[0].message.content.strip()

        except Exception:
            return None
